[package]
name = "weirdfish-server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
clap = { version = "4.5.54", features = ["derive"] }
itertools = "0.14.0"
log = "0.4.29"
tokio = { version = "1.49.0", features = ["full"] }
tower-http = { version = "0.6.8", features = ["fs"] }

[unstable]
features = ["parse_ascii_addr"]
